export function ILLDATA() {
  return [{
    'id': 0,
    'PositionName': '全身症状',
    'HumanSymptomList': [{
      'SymptomID': 639,
      'SymptomName': '低热'
    }, {
      'SymptomID': 888,
      'SymptomName': '发烧'
    }, {
      'SymptomID': 2403,
      'SymptomName': '溃疡'
    }, {
      'SymptomID': 2633,
      'SymptomName': '麻痹'
    }, {
      'SymptomID': 2852,
      'SymptomName': '囊肿'
    }, {
      'SymptomID': 4083,
      'SymptomName': '嗜睡'
    }, {
      'SymptomID': 323,
      'SymptomName': '脾气变坏'
    }, {
      'SymptomID': 4081,
      'SymptomName': '嗜酒'
    }, {
      'SymptomID': 3980,
      'SymptomName': '失眠'
    }, {
      'SymptomID': 5312,
      'SymptomName': '休克'
    }, {
      'SymptomID': 6067,
      'SymptomName': '胀痛'
    }, {
      'SymptomID': 1670,
      'SymptomName': '昏迷'
    }, {
      'SymptomID': 898,
      'SymptomName': '发炎'
    }, {
      'SymptomID': 4860,
      'SymptomName': '喜凉怕热'
    }, {
      'SymptomID': 4249,
      'SymptomName': '水肿'
    }, {
      'SymptomID': 3266,
      'SymptomName': '疲劳'
    }, {
      'SymptomID': 6751,
      'SymptomName': '暴瘦'
    }, {
      'SymptomID': 4034,
      'SymptomName': '食物过敏'
    }, {
      'SymptomID': 462,
      'SymptomName': '抽筋'
    }, {
      'SymptomID': 3867,
      'SymptomName': '神经痛'
    }, {
      'SymptomID': 461,
      'SymptomName': '抽风'
    }, {
      'SymptomID': 4199,
      'SymptomName': '衰弱'
    }, {
      'SymptomID': 459,
      'SymptomName': '抽搐'
    }, {
      'SymptomID': 4239,
      'SymptomName': '水泡'
    }, {
      'SymptomID': 354,
      'SymptomName': '颤抖'
    }, {
      'SymptomID': 4382,
      'SymptomName': '瘫痪'
    }, {
      'SymptomID': 516,
      'SymptomName': '猝死'
    }, {
      'SymptomID': 4777,
      'SymptomName': '无力'
    }, {
      'SymptomID': 898,
      'SymptomName': '发炎'
    }, {
      'SymptomID': 4830,
      'SymptomName': '息肉'
    }, {
      'SymptomID': 787,
      'SymptomName': '恶寒'
    }, {
      'SymptomID': 5321,
      'SymptomName': '虚脱'
    }, {
      'SymptomID': 1380,
      'SymptomName': '骨裂'
    }, {
      'SymptomID': 6536,
      'SymptomName': '虚胖'
    }, {
      'SymptomID': 1472,
      'SymptomName': '过早衰老'
    }, {
      'SymptomID': 6748,
      'SymptomName': '血管堵塞'
    }, {
      'SymptomID': 1673,
      'SymptomName': '浑身酸痛'
    }, {
      'SymptomID': 5788,
      'SymptomName': '抑郁'
    }, {
      'SymptomID': 6683,
      'SymptomName': '浑身发冷'
    }, {
      'SymptomID': 5914,
      'SymptomName': '营养不良'
    }, {
      'SymptomID': 3296,
      'SymptomName': '贫血'
    }, {
      'SymptomID': 6262,
      'SymptomName': '中暑'
    }, {
      'SymptomID': 489,
      'SymptomName': '创伤'
    }, {
      'SymptomID': 421,
      'SymptomName': '痴呆'
    }, {
      'SymptomID': 763,
      'SymptomName': '多疑'
    }, {
      'SymptomID': 801,
      'SymptomName': '噩梦'
    }, {
      'SymptomID': 911,
      'SymptomName': '乏力'
    }, {
      'SymptomID': 6486,
      'SymptomName': '肥胖'
    }, {
      'SymptomID': 915,
      'SymptomName': '烦躁不安'
    }, {
      'SymptomID': 1285,
      'SymptomName': '高血压'
    }, {
      'SymptomID': 4981,
      'SymptomName': '消瘦'
    }, {
      'SymptomID': 5717,
      'SymptomName': '夜游症'
    }, {
      'SymptomID': 6109,
      'SymptomName': '知觉消失'
    }, {
      'SymptomID': 6379,
      'SymptomName': '自恋'
    }
    ]
  }, {
    'id': 1,
    'PositionName': '皮肤症状',
    'HumanSymptomList': [{
      'SymptomID': 463,
      'SymptomName': '臭汗'
    }, {
      'SymptomID': 37,
      'SymptomName': '白头粉刺'
    }, {
      'SymptomID': 4403,
      'SymptomName': '烫伤'
    }, {
      'SymptomID': 466,
      'SymptomName': '出冷汗'
    }, {
      'SymptomID': 973,
      'SymptomName': '肥胖纹'
    }, {
      'SymptomID': 1147,
      'SymptomName': '干性皮肤'
    }, {
      'SymptomID': 1646,
      'SymptomName': '黄疸'
    }, {
      'SymptomID': 3111,
      'SymptomName': '疱疹'
    }, {
      'SymptomID': 5358,
      'SymptomName': '血痂'
    }, {
      'SymptomID': 6368,
      'SymptomName': '紫斑'
    }, {
      'SymptomID': 6517,
      'SymptomName': '灼痛'
    }, {
      'SymptomID': 3722,
      'SymptomName': '瘙痒'
    }, {
      'SymptomID': 87,
      'SymptomName': '斑疹'
    }, {
      'SymptomID': 3477,
      'SymptomName': '轻度烧伤'
    }, {
      'SymptomID': 714,
      'SymptomName': '冻疮'
    }, {
      'SymptomID': 3254,
      'SymptomName': '皮炎'
    }, {
      'SymptomID': 2213,
      'SymptomName': '剧痒'
    }, {
      'SymptomID': 4575,
      'SymptomName': '脱皮'
    }, {
      'SymptomID': 626,
      'SymptomName': '盗汗'
    }, {
      'SymptomID': 3997,
      'SymptomName': '湿疹'
    }, {
      'SymptomID': 701,
      'SymptomName': '冬季皮肤瘙痒'
    }, {
      'SymptomID': 4164,
      'SymptomName': '手足脱皮'
    }, {
      'SymptomID': 1469,
      'SymptomName': '过敏性皮炎'
    }, {
      'SymptomID': 4773,
      'SymptomName': '无胡须腋毛和阴毛'
    }, {
      'SymptomID': 1147,
      'SymptomName': '干性皮肤'
    }, {
      'SymptomID': 1961,
      'SymptomName': '结痂'
    }, {
      'SymptomID': 2779,
      'SymptomName': '面色灰暗'
    }, {
      'SymptomID': 3024,
      'SymptomName': '脓包'
    }, {
      'SymptomID': 3031,
      'SymptomName': '脓疱'
    }, {
      'SymptomID': 3138,
      'SymptomName': '皮肤苍白'
    }, {
      'SymptomID': 3143,
      'SymptomName': '皮肤出现硬块'
    }, {
      'SymptomID': 3148,
      'SymptomName': '皮肤粗糙'
    }, {
      'SymptomID': 3164,
      'SymptomName': '皮肤干燥'
    }, {
      'SymptomID': 3168,
      'SymptomName': '皮肤过敏'
    }, {
      'SymptomID': 3181,
      'SymptomName': '皮肤皲裂'
    }, {
      'SymptomID': 3195,
      'SymptomName': '皮肤搔痒'
    }, {
      'SymptomID': 6496,
      'SymptomName': '皮疹'
    }, {
      'SymptomID': 3218,
      'SymptomName': '皮肤油腻'
    }, {
      'SymptomID': 3570,
      'SymptomName': '雀斑'
    }
    ]
  }, {
    'id': 2,
    'PositionName': '口腔',
    'HumanSymptomList': [{
      'SymptomID': 6597,
      'SymptomName': '舌头溃疡'
    }, {
      'SymptomID': 109,
      'SymptomName': '暴牙'
    }, {
      'SymptomID': 2308,
      'SymptomName': '口臭'
    }, {
      'SymptomID': 6865,
      'SymptomName': '舌头起泡'
    }, {
      'SymptomID': 6888,
      'SymptomName': '嘴唇干裂'
    }, {
      'SymptomID': 2331,
      'SymptomName': '口干渴难忍'
    }, {
      'SymptomID': 509,
      'SymptomName': '唇周边长痘'
    }, {
      'SymptomID': 527,
      'SymptomName': '打哈欠'
    }, {
      'SymptomID': 2185,
      'SymptomName': '咀嚼肌肥大'
    }, {
      'SymptomID': 2337,
      'SymptomName': '口角生疮'
    }, {
      'SymptomID': 2575,
      'SymptomName': '流涎'
    }, {
      'SymptomID': 2793,
      'SymptomName': '磨牙'
    }, {
      'SymptomID': 5476,
      'SymptomName': '牙痛'
    }, {
      'SymptomID': 6888,
      'SymptomName': '嘴唇干裂'
    }
    ]
  }, {
    'id': 3,
    'PositionName': '眼睛',
    'HumanSymptomList': [{
      'SymptomID': 1996,
      'SymptomName': '近视散光'
    }, {
      'SymptomID': 2573,
      'SymptomName': '流泪'
    }, {
      'SymptomID': 2812,
      'SymptomName': '目光呆滞'
    }, {
      'SymptomID': 5556,
      'SymptomName': '眼干'
    }, {
      'SymptomID': 6681,
      'SymptomName': '视力下降'
    }, {
      'SymptomID': 560,
      'SymptomName': '呆滞'
    }, {
      'SymptomID': 6678,
      'SymptomName': '视物模糊'
    }, {
      'SymptomID': 587,
      'SymptomName': '单眼失明'
    }, {
      'SymptomID': 4459,
      'SymptomName': '瞳孔变形'
    }, {
      'SymptomID': 1531,
      'SymptomName': '红色盲'
    }, {
      'SymptomID': 6868,
      'SymptomName': '瞳孔放大'
    }, {
      'SymptomID': 1545,
      'SymptomName': '虹膜发炎'
    }, {
      'SymptomID': 5543,
      'SymptomName': '眼部感染'
    }, {
      'SymptomID': 1916,
      'SymptomName': '角膜溃疡'
    }, {
      'SymptomID': 5556,
      'SymptomName': '眼干'
    }, {
      'SymptomID': 1925,
      'SymptomName': '角膜炎'
    }, {
      'SymptomID': 5626,
      'SymptomName': '眼痛'
    }
    ]
  }, {
    'id': 4,
    'PositionName': '鼻子',
    'HumanSymptomList': [{
      'SymptomID': 133,
      'SymptomName': '鼻出血'
    }, {
      'SymptomID': 180,
      'SymptomName': '鼻塞'
    }, {
      'SymptomID': 156,
      'SymptomName': '鼻孔流脓'
    }, {
      'SymptomID': 145,
      'SymptomName': '鼻干'
    }, {
      'SymptomID': 100,
      'SymptomName': '鼻痒'
    }, {
      'SymptomID': 6640,
      'SymptomName': '鼻酸'
    }, {
      'SymptomID': 6634,
      'SymptomName': '鼻翼发红'
    }
    ]
  }, {
    'id': 5,
    'PositionName': '耳朵',
    'HumanSymptomList': [{
      'SymptomID': 747,
      'SymptomName': '对声音敏感'
    }, {
      'SymptomID': 862,
      'SymptomName': '耳聋'
    }, {
      'SymptomID': 838,
      'SymptomName': '耳冻伤'
    }, {
      'SymptomID': 6650,
      'SymptomName': '耳后长包'
    }, {
      'SymptomID': 6890,
      'SymptomName': '耳朵脱皮'
    }, {
      'SymptomID': 6817,
      'SymptomName': '耳朵长痘'
    }, {
      'SymptomID': 4441,
      'SymptomName': '听觉疲劳'
    }, {
      'SymptomID': 1637,
      'SymptomName': '幻听'
    }, {
      'SymptomID': 830,
      'SymptomName': '耳垂小'
    }, {
      'SymptomID': 827,
      'SymptomName': '耳垂过大'
    }, {
      'SymptomID': 841,
      'SymptomName': '耳根部疼痛'
    }, {
      'SymptomID': 849,
      'SymptomName': '耳后疼痛'
    }, {
      'SymptomID': 866,
      'SymptomName': '耳鸣'
    }
    ]
  }, {
    'id': 6,
    'PositionName': '头部',
    'HumanSymptomList': [{
      'SymptomID': 4379,
      'SymptomName': '太阳穴胀痛'
    }, {
      'SymptomID': 2757,
      'SymptomName': '面部麻木'
    }, {
      'SymptomID': 1529,
      'SymptomName': '红赤面'
    }, {
      'SymptomID': 4520,
      'SymptomName': '头晕'
    }
    ]
  }, {
    'id': 7,
    'PositionName': '咽喉',
    'HumanSymptomList': [{
      'SymptomID': 6485,
      'SymptomName': '扁桃体发炎'
    }, {
      'SymptomID': 1310,
      'SymptomName': '梗噎'
    }, {
      'SymptomID': 1553,
      'SymptomName': '喉部刺痛'
    }, {
      'SymptomID': 1555,
      'SymptomName': '喉部痉挛'
    }, {
      'SymptomID': 1564,
      'SymptomName': '喉咙痒'
    }, {
      'SymptomID': 1563,
      'SymptomName': '喉咙痛'
    }, {
      'SymptomID': 3720,
      'SymptomName': '嗓音粗'
    }, {
      'SymptomID': 3972,
      'SymptomName': '声门短而窄'
    }, {
      'SymptomID': 1561,
      'SymptomName': '喉结增大'
    }, {
      'SymptomID': 1569,
      'SymptomName': '喉头水肿'
    }, {
      'SymptomID': 1571,
      'SymptomName': '喉痒咳嗽'
    }, {
      'SymptomID': 1557,
      'SymptomName': '喉部有痰'
    }, {
      'SymptomID': 3720,
      'SymptomName': '嗓音粗'
    }, {
      'SymptomID': 3977,
      'SymptomName': '声音嘶哑'
    }, {
      'SymptomID': 3979,
      'SymptomName': '失读'
    }, {
      'SymptomID': 1825,
      'SymptomName': '甲状腺肿大'
    }, {
      'SymptomID': 6488,
      'SymptomName': '甲状腺结节'
    }

    ]
  }, {
    'id': 8,
    'PositionName': '颈椎',
    'HumanSymptomList': [{
      'SymptomID': 308,
      'SymptomName': '不能转颈'
    }, {
      'SymptomID': 290,
      'SymptomName': '脖子扭痛'
    }, {
      'SymptomID': 732,
      'SymptomName': '短颈'
    }, {
      'SymptomID': 2116,
      'SymptomName': '颈椎痛'
    }, {
      'SymptomID': 2069,
      'SymptomName': '颈背疼痛'
    }, {
      'SymptomID': 2072,
      'SymptomName': '颈部潮红'
    }, {
      'SymptomID': 6603,
      'SymptomName': '颈椎反弓'
    }, {
      'SymptomID': 6551,
      'SymptomName': '颈部肿瘤'
    }, {
      'SymptomID': 2626,
      'SymptomName': '落枕'
    }, {
      'SymptomID': 2109,
      'SymptomName': '颈椎变形'
    }, {
      'SymptomID': 2080,
      'SymptomName': '颈部扭伤'
    }
    ]
  }, {
    'id': 9,
    'PositionName': '肺',
    'HumanSymptomList': [{
      'SymptomID': 2284,
      'SymptomName': '咳血'
    }, {
      'SymptomID': 1595,
      'SymptomName': '呼吸衰竭'
    }, {
      'SymptomID': 927,
      'SymptomName': '反复肺炎'
    }, {
      'SymptomID': 980,
      'SymptomName': '肺部感染'
    }, {
      'SymptomID': 6856,
      'SymptomName': '肺部疼痛'
    }
    ]
  }, {
    'id': 10,
    'PositionName': '心脏',
    'HumanSymptomList': [{
      'SymptomID': 5095,
      'SymptomName': '心慌'
    }, {
      'SymptomID': 5126,
      'SymptomName': '心力衰竭'
    }, {
      'SymptomID': 5129,
      'SymptomName': '心率不齐'
    }, {
      'SymptomID': 5131,
      'SymptomName': '心率增快'
    }, {
      'SymptomID': 5130,
      'SymptomName': '心率过缓'
    }, {
      'SymptomID': 5180,
      'SymptomName': '心脏骤停'
    }
    ]

  }, {
    'id': 11,
    'PositionName': '呼吸道',
    'HumanSymptomList': [{
      'SymptomID': 1141,
      'SymptomName': '干咳'
    }, {
      'SymptomID': 2274,
      'SymptomName': '咳嗽'
    }, {
      'SymptomID': 3504,
      'SymptomName': '情绪性哮喘'
    }, {
      'SymptomID': 487,
      'SymptomName': '喘息'
    }, {
      'SymptomID': 928,
      'SymptomName': '反复感冒'
    }, {
      'SymptomID': 3344,
      'SymptomName': '气短'
    }, {
      'SymptomID': 3339,
      'SymptomName': '气喘'
    }, {
      'SymptomID': 3358,
      'SymptomName': '气急'
    }, {
      'SymptomID': 4819,
      'SymptomName': '吸气困难'
    }, {
      'SymptomID': 4978,
      'SymptomName': '消化道狭窄'
    }
    ]

  }, {
    'id': 12,
    'PositionName': '肝',
    'HumanSymptomList': [{
      'SymptomID': 1154,
      'SymptomName': '肝部疼痛'
    }, {
      'SymptomID': 1184,
      'SymptomName': '肝气郁结'
    }, {
      'SymptomID': 1165,
      'SymptomName': '肝功能异常'
    }
    ]

  }, {
    'id': 13,
    'PositionName': '胃',
    'HumanSymptomList': [{
      'SymptomID': 110,
      'SymptomName': '暴饮暴食'
    }, {
      'SymptomID': 938,
      'SymptomName': '反胃'
    }, {
      'SymptomID': 792,
      'SymptomName': '恶心'
    }, {
      'SymptomID': 6477,
      'SymptomName': '呕吐'
    }, {
      'SymptomID': 1133,
      'SymptomName': '腹胀'
    }, {
      'SymptomID': 1130,
      'SymptomName': '腹泻'
    }, {
      'SymptomID': 4700,
      'SymptomName': '胃部隐痛'
    }, {
      'SymptomID': 4720,
      'SymptomName': '胃痉挛'
    }, {
      'SymptomID': 4744,
      'SymptomName': '胃痛'
    }, {
      'SymptomID': 4717,
      'SymptomName': '胃寒疼痛'
    }, {
      'SymptomID': 4741,
      'SymptomName': '胃酸过多'
    }, {
      'SymptomID': 6878,
      'SymptomName': '上吐下泻'
    }, {
      'SymptomID': 6479,
      'SymptomName': '干呕'
    }, {
      'SymptomID': 2407,
      'SymptomName': '溃疡疼痛'
    }, {
      'SymptomID': 6490,
      'SymptomName': '反酸'
    }, {
      'SymptomID': 613,
      'SymptomName': '胆汁返流'
    }
    ]

  }, {
    'id': 14,
    'PositionName': '肠',
    'HumanSymptomList': [{
      'SymptomID': 381,
      'SymptomName': '肠痉挛'
    }, {
      'SymptomID': 399,
      'SymptomName': '肠胀气'
    }, {
      'SymptomID': 384,
      'SymptomName': '肠鸣'
    }, {
      'SymptomID': 6083,
      'SymptomName': '阵发性肠绞痛'
    }, {
      'SymptomID': 432,
      'SymptomName': '持续性肠绞痛'
    }
    ]

  }, {
    'id': 15,
    'PositionName': '肾',
    'HumanSymptomList': [{
      'SymptomID': 3897,
      'SymptomName': '肾结石'
    }, {
      'SymptomID': 3902,
      'SymptomName': '肾气虚'
    }, {
      'SymptomID': 3892,
      'SymptomName': '肾功能衰竭'
    }, {
      'SymptomID': 3915,
      'SymptomName': '肾衰竭'
    }, {
      'SymptomID': 6572,
      'SymptomName': '肾痛'
    }, {
      'SymptomID': 3943,
      'SymptomName': '肾脏破裂'
    }
    ]
  }, {
    'id': 16,
    'PositionName': '胸部',
    'HumanSymptomList': [{
      'SymptomID': 294,
      'SymptomName': '不典型胸痛'
    }, {
      'SymptomID': 2510,
      'SymptomName': '连枷胸'
    }, {
      'SymptomID': 2476,
      'SymptomName': '肋痛'
    }, {
      'SymptomID': 2470,
      'SymptomName': '肋骨痛'
    }, {
      'SymptomID': 3243,
      'SymptomName': '皮下气肿'
    }, {
      'SymptomID': 3363,
      'SymptomName': '气胸'
    }, {
      'SymptomID': 2196,
      'SymptomName': '巨乳'
    }, {
      'SymptomID': 5277,
      'SymptomName': '胸闷'
    }, {
      'SymptomID': 6574,
      'SymptomName': '胸闷气短'
    }, {
      'SymptomID': 5278,
      'SymptomName': '胸闷憋气'
    }, {
      'SymptomID': 57,
      'SymptomName': '侧肋骨痛'
    }, {
      'SymptomID': 6451,
      'SymptomName': '左胸痛'
    }, {
      'SymptomID': 5979,
      'SymptomName': '右胸痛'
    }, {
      'SymptomID': 754,
      'SymptomName': '多根肋骨骨折'
    }, {
      'SymptomID': 6241,
      'SymptomName': '窒息'
    }
    ]

  }, {
    'id': 17,
    'PositionName': '腰腹部',
    'HumanSymptomList': [{
      'SymptomID': 6480,
      'SymptomName': '腰痛'
    }, {
      'SymptomID': 5657,
      'SymptomName': '腰背痛'
    }, {
      'SymptomID': 2426,
      'SymptomName': '阑尾脓肿'
    }, {
      'SymptomID': 5654,
      'SymptomName': '腰背刺痛'
    }, {
      'SymptomID': 5656,
      'SymptomName': '腰背酸痛'
    }, {
      'SymptomID': 2114,
      'SymptomName': '颈椎间盘突出'
    }, {
      'SymptomID': 3267,
      'SymptomName': '啤酒肚'
    }, {
      'SymptomID': 6543,
      'SymptomName': '腰椎疼痛'
    }, {
      'SymptomID': 6438,
      'SymptomName': '左、右腰腹痛'
    }, {
      'SymptomID': 3279,
      'SymptomName': '脾虚'
    }, {
      'SymptomID': 2425,
      'SymptomName': '阑尾感染'
    }, {
      'SymptomID': 6257,
      'SymptomName': '中上腹痛'
    }, {
      'SymptomID': 4896,
      'SymptomName': '下腹疼痛'
    }, {
      'SymptomID': 4897,
      'SymptomName': '下腹痛'
    }, {
      'SymptomID': 4898,
      'SymptomName': '下腹胀痛'
    }, {
      'SymptomID': 4893,
      'SymptomName': '下腹绞痛'
    }, {
      'SymptomID': 1087,
      'SymptomName': '腹部不适'
    }
    ]

  }, {
    'id': 18,
    'PositionName': '上肢',
    'HumanSymptomList': [{
      'SymptomID': 246,
      'SymptomName': '臂痛'
    }, {
      'SymptomID': 6581,
      'SymptomName': '胳膊疼痛'
    }, {
      'SymptomID': 426,
      'SymptomName': '持物不稳'
    }, {
      'SymptomID': 6858,
      'SymptomName': '手指淤血'
    }, {
      'SymptomID': 6571,
      'SymptomName': '手臂发麻'
    }, {
      'SymptomID': 4882,
      'SymptomName': '下垂肩'
    }, {
      'SymptomID': 6305,
      'SymptomName': '肘痛'
    }, {
      'SymptomID': 4154,
      'SymptomName': '手指扭伤'
    }, {
      'SymptomID': 4103,
      'SymptomName': '手抽筋'
    }, {
      'SymptomID': 4112,
      'SymptomName': '手麻'
    }, {
      'SymptomID': 6774,
      'SymptomName': '指甲脱落'
    }, {
      'SymptomID': 4141,
      'SymptomName': '手震颤'
    }, {
      'SymptomID': 6204,
      'SymptomName': '指甲夹伤'
    }, {
      'SymptomID': 4142,
      'SymptomName': '手指不能屈伸'
    }, {
      'SymptomID': 577,
      'SymptomName': '单纯骨折'
    }, {
      'SymptomID': 4155,
      'SymptomName': '手指痛风'
    }, {
      'SymptomID': 1861,
      'SymptomName': '肩关节痛'
    }, {
      'SymptomID': 6836,
      'SymptomName': '食指发麻'
    }, {
      'SymptomID': 1870,
      'SymptomName': '肩痛'
    }, {
      'SymptomID': 6840,
      'SymptomName': '手背长斑'
    }, {
      'SymptomID': 1795,
      'SymptomName': '季节性手脱皮'
    }, {
      'SymptomID': 6852,
      'SymptomName': '手腕骨折'
    }, {
      'SymptomID': 4107,
      'SymptomName': '手冻伤'
    }, {
      'SymptomID': 6857,
      'SymptomName': '手指僵硬'
    }, {
      'SymptomID': 4111,
      'SymptomName': '手凉'
    }, {
      'SymptomID': 4641,
      'SymptomName': '腕部疼痛'
    }, {
      'SymptomID': 4121,
      'SymptomName': '手酸'
    }, {
      'SymptomID': 4123,
      'SymptomName': '手脱皮'
    }
    ]
  }, {
    'id': 19,
    'PositionName': '下肢',
    'HumanSymptomList': [{
      'SymptomID': 225,
      'SymptomName': '扁平足'
    }, {
      'SymptomID': 18,
      'SymptomName': '八字脚步态'
    }, {
      'SymptomID': 2800,
      'SymptomName': '拇外翻'
    }, {
      'SymptomID': 6616,
      'SymptomName': '腿痛'
    }, {
      'SymptomID': 6876,
      'SymptomName': '腿脚发麻'
    }, {
      'SymptomID': 4543,
      'SymptomName': '腿脚抽筋'
    }, {
      'SymptomID': 4930,
      'SymptomName': '下肢无力'
    }, {
      'SymptomID': 5048,
      'SymptomName': '小腿酸痛'
    }, {
      'SymptomID': 1937,
      'SymptomName': '脚底干裂'
    }, {
      'SymptomID': 6653,
      'SymptomName': '出脚汗'
    }, {
      'SymptomID': 304,
      'SymptomName': '不能屈膝'
    }, {
      'SymptomID': 4838,
      'SymptomName': '膝盖撞伤'
    }, {
      'SymptomID': 549,
      'SymptomName': '大腿刺痛'
    }, {
      'SymptomID': 4887,
      'SymptomName': '下蹲困难'
    }, {
      'SymptomID': 553,
      'SymptomName': '大腿外侧痛'
    }, {
      'SymptomID': 1727,
      'SymptomName': '鸡眼'
    }, {
      'SymptomID': 6540,
      'SymptomName': '大腿酸痛'
    }, {
      'SymptomID': 1936,
      'SymptomName': '脚臭'
    }, {
      'SymptomID': 6547,
      'SymptomName': '大腿内侧痛'
    }, {
      'SymptomID': 1940,
      'SymptomName': '脚气'
    }, {
      'SymptomID': 6549,
      'SymptomName': '大腿内侧瘙痒'
    }, {
      'SymptomID': 6756,
      'SymptomName': '脚痒'
    }, {
      'SymptomID': 6553,
      'SymptomName': '大腿疼痛'
    }, {
      'SymptomID': 1937,
      'SymptomName': '脚底干裂'
    }, {
      'SymptomID': 5046,
      'SymptomName': '小腿瘙痒干燥'
    }, {
      'SymptomID': 1938,
      'SymptomName': '脚冻伤'
    }, {
      'SymptomID': 5047,
      'SymptomName': '小腿水肿'
    }, {
      'SymptomID': 6409,
      'SymptomName': '足底脱皮'
    }, {
      'SymptomID': 6835,
      'SymptomName': '小腿乏力'
    }, {
      'SymptomID': 6423,
      'SymptomName': '足癣'
    }
    ]
  }, {
    'id': 20,
    'PositionName': '背部',
    'HumanSymptomList': [{
      'SymptomID': 116,
      'SymptomName': '背部痉挛'
    }, {
      'SymptomID': 6758,
      'SymptomName': '背胀'
    }, {
      'SymptomID': 117,
      'SymptomName': '背部酸痛'
    }, {
      'SymptomID': 119,
      'SymptomName': '背脊痛'
    }, {
      'SymptomID': 120,
      'SymptomName': '背痛'
    }, {
      'SymptomID': 4580,
      'SymptomName': '驼背'
    }
    ]
  }, {
    'id': 21,
    'PositionName': '排泄部',
    'HumanSymptomList': [{
      'SymptomID': 232,
      'SymptomName': '便秘'
    }, {
      'SymptomID': 6607,
      'SymptomName': '大便干燥'
    }, {
      'SymptomID': 555,
      'SymptomName': '大小便失禁'
    }, {
      'SymptomID': 4574,
      'SymptomName': '脱肛'
    }, {
      'SymptomID': 1236,
      'SymptomName': '肛门剧痛'
    }, {
      'SymptomID': 1227,
      'SymptomName': '肛裂'
    }, {
      'SymptomID': 1230,
      'SymptomName': '肛门病变'
    }, {
      'SymptomID': 1246,
      'SymptomName': '肛门坠胀'
    }, {
      'SymptomID': 1042,
      'SymptomName': '粪便量多'
    }, {
      'SymptomID': 3104,
      'SymptomName': '排气障碍'
    }, {
      'SymptomID': 1043,
      'SymptomName': '粪便量少'
    }, {
      'SymptomID': 1241,
      'SymptomName': '肛门外翻'
    }, {
      'SymptomID': 1239,
      'SymptomName': '肛门松弛'
    }, {
      'SymptomID': 1684,
      'SymptomName': '肛门瘙痒'
    }, {
      'SymptomID': 6238,
      'SymptomName': '痔出血'
    }, {
      'SymptomID': 3088,
      'SymptomName': '排便困难'
    }, {
      'SymptomID': 3091,
      'SymptomName': '排便障碍'
    }, {
      'SymptomID': 3090,
      'SymptomName': '排便时间过长'
    }, {
      'SymptomID': 3092,
      'SymptomName': '排出结石'
    }, {
      'SymptomID': 3103,
      'SymptomName': '排气多'
    }
    ]
  }, {
    'id': 22,
    'PositionName': '男性生殖',
    'HumanSymptomList': [{
      'SymptomID': 2834,
      'SymptomName': '男性不育'
    }, {
      'SymptomID': 2840,
      'SymptomName': '男性性早熟'
    }, {
      'SymptomID': 6510,
      'SymptomName': '包皮水肿'
    }, {
      'SymptomID': 6732,
      'SymptomName': '包皮红肿'
    }, {
      'SymptomID': 1291,
      'SymptomName': '睾丸发育不全'
    }, {
      'SymptomID': 1293,
      'SymptomName': '睾丸疼痛'
    }, {
      'SymptomID': 3403,
      'SymptomName': '前列腺结石'
    }, {
      'SymptomID': 5871,
      'SymptomName': '隐睾'
    }, {
      'SymptomID': 6521,
      'SymptomName': '阴囊潮湿'
    }, {
      'SymptomID': 5848,
      'SymptomName': '阴茎疼痛'
    }, {
      'SymptomID': 5763,
      'SymptomName': '遗精'
    }, {
      'SymptomID': 2065,
      'SymptomName': '精子稀少'
    }, {
      'SymptomID': 2053,
      'SymptomName': '精液稠'
    }, {
      'SymptomID': 6734,
      'SymptomName': '包皮开裂'
    }, {
      'SymptomID': 5857,
      'SymptomName': '阴囊水肿'
    }, {
      'SymptomID': 1290,
      'SymptomName': '睾丸触痛'
    }, {
      'SymptomID': 5860,
      'SymptomName': '阴囊肿胀'
    }, {
      'SymptomID': 1297,
      'SymptomName': '睾丸胀痛'
    }, {
      'SymptomID': 5850,
      'SymptomName': '阴茎异常'
    }, {
      'SymptomID': 2055,
      'SymptomName': '精液发黄'
    }, {
      'SymptomID': 2056,
      'SymptomName': '精液量多'
    }, {
      'SymptomID': 2057,
      'SymptomName': '精液少'
    }, {
      'SymptomID': 2065,
      'SymptomName': '精子稀少'
    }, {
      'SymptomID': 2062,
      'SymptomName': '精子活力低'
    }, {
      'SymptomID': 2067,
      'SymptomName': '精子质量下降'
    }, {
      'SymptomID': 2836,
      'SymptomName': '男性小便刺痛'
    }, {
      'SymptomID': 3835,
      'SymptomName': '射精疼'
    }, {
      'SymptomID': 6794,
      'SymptomName': '前列腺快感'
    }, {
      'SymptomID': 4175,
      'SymptomName': '输精管疼痛'
    }
    ]
  }, {
    'id': 23,
    'PositionName': '女性生殖',
    'HumanSymptomList': [{
      'SymptomID': 759,
      'SymptomName': '多囊卵巢'
    }, {
      'SymptomID': 345,
      'SymptomName': '产后子宫收缩'
    }, {
      'SymptomID': 28,
      'SymptomName': '白带增多'
    }, {
      'SymptomID': 6483,
      'SymptomName': '白带异常'
    }, {
      'SymptomID': 1332,
      'SymptomName': '宫腔积脓'
    }, {
      'SymptomID': 1320,
      'SymptomName': '宫颈闭锁'
    }, {
      'SymptomID': 1666,
      'SymptomName': '会阴部撕裂感'
    }, {
      'SymptomID': 2619,
      'SymptomName': '卵巢性多毛'
    }, {
      'SymptomID': 2570,
      'SymptomName': '流产'
    }, {
      'SymptomID': 2615,
      'SymptomName': '卵巢功能障碍'
    }, {
      'SymptomID': 4472,
      'SymptomName': '痛经'
    }, {
      'SymptomID': 4447,
      'SymptomName': '停经'
    }, {
      'SymptomID': 5979,
      'SymptomName': '月经量多'
    }, {
      'SymptomID': 6346,
      'SymptomName': '子宫穿孔'
    }, {
      'SymptomID': 6502,
      'SymptomName': '月经推迟'
    }, {
      'SymptomID': 3044,
      'SymptomName': '女性不孕'
    }, {
      'SymptomID': 6484,
      'SymptomName': '月经不调'
    }, {
      'SymptomID': 4177,
      'SymptomName': '输卵管肿大'
    }, {
      'SymptomID': 6586,
      'SymptomName': '白带带血'
    }, {
      'SymptomID': 6641,
      'SymptomName': '外阴干涩'
    }, {
      'SymptomID': 6589,
      'SymptomName': '白带异味'
    }, {
      'SymptomID': 5234,
      'SymptomName': '性交疼痛'
    }, {
      'SymptomID': 333,
      'SymptomName': '产后出血'
    }, {
      'SymptomID': 5829,
      'SymptomName': '阴道裂伤'
    }, {
      'SymptomID': 1328,
      'SymptomName': '宫颈水肿'
    }, {
      'SymptomID': 5820,
      'SymptomName': '阴道不规则出血'
    }, {
      'SymptomID': 1323,
      'SymptomName': '宫颈糜烂'
    }, {
      'SymptomID': 5824,
      'SymptomName': '阴道出血'
    }, {
      'SymptomID': 1324,
      'SymptomName': '宫颈囊肿'
    }, {
      'SymptomID': 6358,
      'SymptomName': '子宫松弛'
    }, {
      'SymptomID': 6514,
      'SymptomName': '外阴瘙痒'
    }, {
      'SymptomID': 6359,
      'SymptomName': '子宫下垂'
    }, {
      'SymptomID': 2018,
      'SymptomName': '经期提前'
    }, {
      'SymptomID': 2020,
      'SymptomName': '经期推迟'
    }, {
      'SymptomID': 2017,
      'SymptomName': '经期缩短'
    }, {
      'SymptomID': 2220,
      'SymptomName': '绝经'
    }, {
      'SymptomID': 2616,
      'SymptomName': '卵巢囊肿'
    }
    ]
  }, {
    'id': 24,
    'PositionName': '膀胱',
    'HumanSymptomList': [{
      'SymptomID': 2981,
      'SymptomName': '尿频'
    }, {
      'SymptomID': 2969,
      'SymptomName': '尿急'
    }, {
      'SymptomID': 2994,
      'SymptomName': '尿痛'
    }, {
      'SymptomID': 6566,
      'SymptomName': '尿无力'
    }, {
      'SymptomID': 6673,
      'SymptomName': '尿等待'
    }
    ]
  }];
}